### ISSUE TITLE
Can Termination 

### ISSUE THREAD

**Issue by djgabriel2004** [collin80/esp32_can#37]
Hi, this is not related with the code but more with the HW,  is there any way to remove the 120ohm resistor? My bus already has one and I think that’s the reason to random and slow messages pass Thru 

thanks

**Comment by collin80** [comment]
You can unsolder them. Sorry, there isn't any selective termination on the board. We should have added solder jumpers or switches or something but didn't. Usually three terminations isn't a problem on a CAN bus but by the time you get to 4 or more it gets a bit crazy. Even still, 3 may be too many in some circumstances so I can see why you might want to remove the termination. On the official board (the one with my name on it) the termination is R2, R3, R13, R14. It's split termination (that is, two 60 ohm resistors in series with a capacitor to ground in between them). You can remove just one of the resistors and that's good enough to remove termination.
