### ISSUE TITLE
Issue importing freertos/FreeRTOS.h

### ISSUE THREAD

**Issue by msauvayre** [collin80/esp32_can#49]
Hi, 
I have an issue with the library mentionned in object.
Could you mention which version of the library I have to use with your library :
The one from https://github.com/feilipu/Arduino_FreeRTOS_Library ?
The one from https://github.com/maniacbug/FreeRTOS ?

complete tracking in Arduino IDE 2.1.0 :
In file included from C:\Users\xxxxx\Documents\Arduino\libraries\ESP32_CAN\src/esp32_can.h:1:0,
                 from C:\Users\xxxx\Documents\Arduino\esp32_can_shield_sample_code\esp32_can_shield_sample_code.ino:1:
C:\Users\xxxx\Documents\Arduino\libraries\ESP32_CAN\src/esp32_can_builtin.h:36:10: fatal error: freertos/FreeRTOS.h: No such file or directory
 #include "freertos/FreeRTOS.h"
thanks

**Comment by TurboMarian** [comment]
Hi,
Did you solve the problem?
